-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES
-- Extends the default Supabase auth.users table
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role_type text check (role_type in ('Hacker', 'Hustler', 'Designer', 'Mentor')),
  bio text,
  skills text[], -- Array of strings e.g. ['React', 'Python']
  values_tags text[], -- Array of strings e.g. ['Climate', 'DeFi']
  avatar_url text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 2. VISION CARDS
-- The core "items" users swipe on
create table public.vision_cards (
  id uuid default uuid_generate_v4() primary key,
  creator_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  summary text not null,
  pitch_deck_url text,
  required_roles text[], -- e.g. ['Designer', 'Marketing']
  tags text[], -- e.g. ['SaaS', 'EdTech']
  commitment_level text,
  status text default 'active' check (status in ('active', 'paused', 'closed')),
  created_at timestamp with time zone default now()
);

-- 3. SWIPES
-- Tracks every interaction to prevent duplicate cards and build the graph
create table public.swipes (
  id bigint generated by default as identity primary key,
  swiper_id uuid references public.profiles(id) on delete cascade not null,
  card_id uuid references public.vision_cards(id) on delete cascade not null,
  direction text check (direction in ('left', 'right')) not null,
  created_at timestamp with time zone default now(),
  unique(swiper_id, card_id) -- Composite unique constraint
);

-- 4. MATCHES
-- Successful connections. 
create table public.matches (
  id uuid default uuid_generate_v4() primary key,
  card_id uuid references public.vision_cards(id) not null,
  seeker_id uuid references public.profiles(id) not null, -- The person who swiped right
  founder_id uuid references public.profiles(id) not null, -- The owner of the card
  synergy_score int default 0,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- 5. MESSAGES (Threads & Content)
create table public.threads (
  id uuid default uuid_generate_v4() primary key,
  match_id uuid references public.matches(id) on delete cascade,
  updated_at timestamp with time zone default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  thread_id uuid references public.threads(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default now()
);

-- 6. COMMUNITY FEED (Posts & Comments)
create table public.posts (
  id uuid default uuid_generate_v4() primary key,
  author_id uuid references public.profiles(id) not null,
  content text not null,
  likes_count int default 0,
  created_at timestamp with time zone default now()
);

create table public.comments (
  id bigint generated by default as identity primary key,
  post_id uuid references public.posts(id) on delete cascade,
  author_id uuid references public.profiles(id),
  content text not null,
  created_at timestamp with time zone default now()
);

-- 7. EVENTS
create table public.events (
  id uuid default uuid_generate_v4() primary key,
  organizer_id uuid references public.profiles(id),
  title text not null,
  description text,
  location text,
  start_time timestamp with time zone not null,
  capacity int default 50,
  created_at timestamp with time zone default now()
);

create table public.event_rsvps (
  event_id uuid references public.events(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  status text check (status in ('confirmed', 'waitlist', 'cancelled')),
  created_at timestamp with time zone default now(),
  primary key (event_id, user_id)
);

-- ----------------------------
-- PERFORMANCE INDEXES
-- ----------------------------

-- Speed up the "Feed" query (Finding cards not yet swiped)
create index idx_swipes_swiper_card on public.swipes (swiper_id, card_id);

-- Speed up Tag Matching (GIN Index for Arrays)
create index idx_profiles_skills on public.profiles using gin (skills);
create index idx_vision_cards_tags on public.vision_cards using gin (tags);
create index idx_vision_cards_roles on public.vision_cards using gin (required_roles);

-- Speed up Message retrieval
create index idx_messages_thread_created on public.messages (thread_id, created_at);

-- Speed up Feed sorting
create index idx_posts_created_at on public.posts (created_at desc);
